# **Yallara (Lesser Bilby)** *(Macrotis leucura)* 

[Genome & Transcriptome Data ](https://threatenedspecies.s3.ap-southeast-2.amazonaws.com/index.html) | [NCBI Accession: 		PRJNA1049868](https://www.ncbi.nlm.nih.gov/bioproject/1049868)

[Publication:](https://www.nature.com/articles/s41559-024-02436-2)  Carolyn J. Hogg, Richard J. Edwards, Katherine A. Farquharson, Luke W. Silver, Parice Brandies, Emma Peel, Merly Escalona, Frederick R. Jaya, Rujiporn Thavornkanlapachai, Kimberley Batley, Tessa M. Bradford, J King Chang, Zhiliang Chen, Nandan Deshpande, Martin Dziminski, Kyle M. Ewart, Oliver W. Griffith, Laia Marin-Gual, Katherine L. Moon, Kenny J. Travouillon, Paul Waters Camilla M. Whittington, Marc R. Wilkins, Kristofer M. Helgen, Nathan Lo, Simon Y. W. Ho, Aurora Ruiz Herrera, Rachel Paltridge, Jennifer A. Marshall Graves, Marilyn Renfree, Beth Shapiro, Kym Ottewell, Kiwirrkurra Rangers, Katherine Belov. (2024) Extant and extinct bilby genomes combined with Indigenous knowledge improve conservation of a unique Australian marsupial. Nature Ecology & Evolution DOI: 10.1038/s41559-024-02436-2

Download data through hyperlinks above or using the [AWS Command Line Interface](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html)
  
```
aws s3 cp s3://threatenedspecies/Macrotis_leucura/lesser_20230510_r1polish.fasta.gz .
aws s3 cp s3://threatenedspecies/Macrotis_leucura/PE8853A1_all_Jan2023_markdupreadgroups.bam .
aws s3 cp s3://threatenedspecies/Macrotis_leucura/PE8853A2_all_Jan2023_markdupreadgroups.bam .
aws s3 cp s3://threatenedspecies/Macrotis_leucura/PEE8853A7L003_all_Jan2023_markdupreadgroups.bam .
aws s3 cp s3://threatenedspecies/Macrotis_leucura/PEE8853A9L003_all_Jan2023_markdupreadgroups.bam .
aws s3 sync s3://threatenedspecies/Macrotis_leucura/ .
```

<br>

| Assembly Statistics |  |
|:--- | --- |
| Assembly    | lesser_20230510_r1polish.fasta.gz  |
| Description |  Consensus polished sequence of PE8853A2 |
| Genome size | 3.50 Gb | 
| #contigs | 6,329,012 | 
| contig N50 | 851 bp | 
| # scaffolds | 10 | 
| Scaffold N50 | 343.85 Mb | 
| Largest Scaffold | 934 Mb |
| Gap % | 19.74 % |

The yallara reference assembly was generated by obtaining the consensus sequence of PE8853A2 aligned to the 9 autosomes and mitogenome of the Ninu and polished using pilon
<br>

| **BUSCO** | **v5.4.6 mammalia_obd10** |
|:--- | --- |
| Genes    | 9226 |
| Complete    | 85.5% |
 

We acknowledge the traditional custodians of the land upon which bilbies have been, and are still, found and pay respects to their elders past and present. 
The lesser bilby samples were provided by the Natural History Museum, London (NHMUK), South Australian Museum (SAMA) and Museum Victoria (NMV). 

Image supplied by Kenny Travouillon, WA museum
